name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'main' }} then job3
    steps:
         - uses: actions/checkout@v3
         - name: Use
    
  job2:
    needs: job1
    runs-on: ubuntu-latest
    environment: production
    strategy:
        matrix:
          node-version: [16.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
          - uses: actions/checkout@v3
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
          - run: npm install -g @angular/cli
          - run : npm install --force
          - run: npm run build
  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g @angular/cli
      - run : npm install --force
      - run: npm run build
